replicaCount: 1

image:
  repository: jensen1804/devopsified-go-app
  nullPolicy: IfNotPresent
  tag: "1.0"

ingress:
  enabled: false
  className: ""
  annotations: {} 
  hosts:
    - hosts: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific 